#!./venv/bin/python
# -*- coding: utf-8 -*-

"""empty message

Revision ID: 2e9e81efe544
Revises: bfcafce07ea9
Create Date: 2023-09-06 21:12:47.352362

"""

# pylint: disable=C0103,C0116,E1101

# Third-party
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e9e81efe544'
down_revision = 'bfcafce07ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column(
            'priority',
            sa.Enum('RELAXED', 'MEDIUM', 'TIGHT', name='prioritylevel'),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('OPEN', 'IN_WORK', 'COMPLETED', 'DISCARD', name='taskstatus'),
            nullable=False,
        ),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('completion_date', sa.DateTime(), nullable=True),
        sa.Column('recurring_task', sa.Boolean(), nullable=True),
        sa.Column('estimate', sa.Integer(), nullable=True),
        sa.Column('actual_time_spent', sa.Integer(), nullable=True),
        sa.Column('type', sa.Enum('TASK', 'SUBTASK', name='tasktype'), nullable=False),
        sa.ForeignKeyConstraint(
            ['assigned_to_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    op.create_table(
        'comments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['tasks.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('tasks')
    # ### end Alembic commands ###
